gen:
  dsn:
  dst: mysql
  env: prod
  logFile: gen.log

sys:
  dst: mysql
  dsn: root:flzx3kc@qwe@tcp(119.91.40.151:3306)/turing?charset=utf8mb4&parseTime=true&local=Local
  env: prod
  logFile: sys.log
  